site_name: Workshop - Estrutura Dados

theme:
  name: material
  palette:
    primary: blue

repo_name: "luizweb/workshop_estrutura"
repo_url: "https://github.com/luizweb/workshop_estrutura"

#nav:
  #- Home: index.md
  #- API: api.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

plugins:
  - search
  - mkdocstrings:
      default_handler: python
